### ISSUE TITLE
IllegalArgumentException: null is not a sub type of TypeName

### ISSUE THREAD

**Issue by fommil** [propensive/magnolia#117]
What looks like a `.knownSubTypes` bug...

In this code https://gitlab.com/fommil/scalaz-deriving/merge_requests/195 (possibly `master` when you read this) the file `GeoJSONBenchmarks.scala` has a commented out test because it causes this exception

```
[info] java.lang.IllegalArgumentException: The given value `null` is not a sub type of `TypeName(jsonformat.benchmarks.m,GeoJSON)`
[info] 	at magnolia.SealedTrait.rec$1(interface.scala:223)
[info] 	at magnolia.SealedTrait.dispatch(interface.scala:225)
[info] 	at jsonformat.MagnoliaEncoder$.$anonfun$dispatch$1(Magnolia.scala:26)
```

in this codepath

```scala
  def dispatch[A](ctx: SealedTrait[JsEncoder, A]): JsEncoder[A] =
    a =>
      ctx.dispatch(a) { sub =>
        val hint = "type" -> JsString(sub.typeName.short)
        ...
      }
```

for an ADT that looks like

```scala
  sealed abstract class Geometry
  final case class Point(coordinates: (Double, Double)) extends Geometry
  final case class MultiPoint(coordinates: List[(Double, Double)])
      extends Geometry
  final case class LineString(coordinates: List[(Double, Double)])
      extends Geometry
  final case class MultiLineString(
    coordinates: List[List[(Double, Double)]]
  ) extends Geometry
  final case class Polygon(coordinates: List[List[(Double, Double)]])
      extends Geometry
  final case class MultiPolygon(
    coordinates: List[List[List[(Double, Double)]]]
  ) extends Geometry
  final case class GeometryCollection(geometries: List[Geometry])
      extends Geometry

  sealed abstract class GeoJSON
  final case class Feature(properties: Map[String, String], geometry: Geometry)
      extends GeoJSON
  final case class FeatureCollection(features: List[GeoJSON]) extends GeoJSON
```

**Comment by fommil** [comment]
interestingly, this is fixed if I use `@deriving`... but that's just a workaround, there is a fundamental bug here I suspect.

To reproduce, go back to the commit where it is exhibited: https://gitlab.com/fommil/scalaz-deriving/tree/4bbc8194a51d3906b4a5adbfdae9a858d424d9af

**Comment by fommil** [comment]
I've not seen this in a while.
