### ISSUE TITLE
Magnolia requires `scala-reflect` classes at runtime because spliced code references methods in `Magnolia$` object

### ISSUE THREAD

**Issue by neko-kai** [propensive/magnolia#234]
To reproduce execute:

```
git clone https://github.com/7mind/distage-example/
cd distage-example
git checkout magnolia-keepLeft-noclassdefexception
sbt 'runMain leaderboard.MainDummy'
```

Result error:

```
[error] java.lang.NoClassDefFoundError: scala/reflect/api/TypeCreator
[error] 	at leaderboard.plugins.LeaderboardPlugin$.<clinit>(LeaderboardPlugin.scala:19)
[error] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
[error] 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1045)
[error] 	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
[error] 	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
[error] 	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
[error] 	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
[error] 	at java.base/java.lang.reflect.Field.get(Field.java:418)
[error] 	at izumi.distage.plugins.load.PluginLoaderDefaultImpl$.$anonfun$doLoad$9(PluginLoaderDefaultImpl.scala:78)
[error] 	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
[error] 	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
[error] 	at scala.collection.mutable.ArrayBuffer.flatMap(ArrayBuffer.scala:40)
[error] 	at izumi.distage.plugins.load.PluginLoaderDefaultImpl$.doLoad(PluginLoaderDefaultImpl.scala:74)
[error] 	at izumi.distage.plugins.load.PluginLoaderDefaultImpl.loadPkgs$1(PluginLoaderDefaultImpl.scala:31)
[error] 	at izumi.distage.plugins.load.PluginLoaderDefaultImpl.$anonfun$scanClasspath$3(PluginLoaderDefaultImpl.scala:42)
[error] 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:434)
[error] 	at izumi.fundamentals.platform.cache.SyncCache.getOrCompute(SyncCache.scala:15)
[error] 	at izumi.distage.plugins.load.PluginLoaderDefaultImpl.$anonfun$scanClasspath$2(PluginLoaderDefaultImpl.scala:42)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:265)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:79)
[error] 	at izumi.distage.plugins.load.PluginLoaderDefaultImpl.scanClasspath(PluginLoaderDefaultImpl.scala:40)
[error] 	at izumi.distage.plugins.load.PluginLoaderDefaultImpl.load(PluginLoaderDefaultImpl.scala:16)
[error] 	at izumi.distage.roles.RoleAppLauncherImpl.launch(RoleAppLauncherImpl.scala:76)
[error] 	at izumi.distage.roles.RoleAppMain.main(RoleAppMain.scala:26)
[error] 	at leaderboard.MainDummy.main(LeaderboardRole.scala)
[error] Caused by: java.lang.ClassNotFoundException: scala.reflect.api.TypeCreator
[error] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
[error] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	... 25 more
[error] Nonzero exit code returned from runner: 1
[error] (Compile / runMain) Nonzero exit code returned from runner: 1
```

[Offending line](https://github.com/7mind/distage-example/blob/magnolia-keepLeft-noclassdefexception/src/main/scala/leaderboard/plugins/LeaderboardPlugin.scala#L19):

```scala
  Magnolia.keepLeft(Left(()))
```

Why:

Calling `Magnolia.keepLeft` forces creation of `Magnolia` object which contains definitions of macro methods that reference `scala-reflect` classes. `keepLeft` & `checkParamLenghts` are spliced in code of instances generated by magnolia, so all uses of magnolia require `scala-reflect` library at runtime.

Possible fix:

Move all methods spliced to user code in a separate object, even nested inside Magnolia it will work, e.g. `Magnolia.utils`. Keep old methods as `private[magnolia]` to preserve binary compatibility.

/cc @joroKr21 @propensive

**Comment by propensive** [comment]
Just seen this in the wrong order... Please ignore the comment on my review, @neko-kai!
